[tool:pytest]
testpaths = tests
norecursedirs = .git testing_config
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
addopts = 
    --strict-markers
    --disable-warnings
    --cov=custom_components.rental_control
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=100

